"""Публичные ошибки raclib в асинхронной ветке.

Единый источник правды — :mod:`raclib.errors`; здесь тот же набор классов,
чтобы работали импорты вида ``from raclib.asynchronous.errors import ...``.
"""

from ..errors import (  # noqa: F401 - реэкспорт публичного API
    AgentAdminCreateError,
    AgentAdminNotFoundError,
    AgentAdminsNotFoundError,
    AgentCredentialsError,
    CentralServerCredentialsError,
    ClusterCredentialsError,
    ClusterNotFoundError,
    ClustersNotFoundError,
    ConnectionError,
    CounterNotFoundError,
    CreateInfobaseParamsError,
    DatabaseConnectionError,
    DatabaseError,
    IncorrectVersionError,
    InfobaseAlreadyExistsError,
    InfobaseCredentialsError,
    InfobaseDatabaseNotFoundError,
    InfobaseNotFoundError,
    LimitNotFoundError,
    ParamError,
    PortConflictError,
    RACInvocationError,
    RACNotFoundError,
    RACTimeoutError,
    RuleNotFoundError,
    ServerAlreadyExistsError,
    ServerIPRangeError,
    ServerIsMainError,
    ServerNotCentralError,
    UnknownError,
    UnknownHostError,
    errors,
    handler,
)

__all__ = [
    "errors",
    "handler",
    "UnknownError",
    "RACNotFoundError",
    "RACInvocationError",
    "RACTimeoutError",
    "ClusterNotFoundError",
    "ClustersNotFoundError",
    "InfobaseNotFoundError",
    "InfobaseCredentialsError",
    "InfobaseDatabaseNotFoundError",
    "InfobaseAlreadyExistsError",
    "ClusterCredentialsError",
    "CentralServerCredentialsError",
    "AgentCredentialsError",
    "AgentAdminNotFoundError",
    "AgentAdminsNotFoundError",
    "AgentAdminCreateError",
    "ConnectionError",
    "CreateInfobaseParamsError",
    "DatabaseConnectionError",
    "DatabaseError",
    "IncorrectVersionError",
    "ParamError",
    "PortConflictError",
    "UnknownHostError",
    "CounterNotFoundError",
    "LimitNotFoundError",
    "RuleNotFoundError",
    "ServerAlreadyExistsError",
    "ServerIPRangeError",
    "ServerIsMainError",
    "ServerNotCentralError",
]
